//generated by edc2pps on 2021-12-30 14:28:11.343674+00:00

#[cfg(feature = "pic32mx1xxfxxxb")]
pps_tables! {
    { // virtual input declarations
        Int4, int4;   // PPS group #1
        T2ck, t2ck;   // PPS group #1
        Ic4, ic4;   // PPS group #1
        Ss1, ss1;   // PPS group #1
        Refclki, refclki;   // PPS group #1
        Int3, int3;   // PPS group #2
        T3ck, t3ck;   // PPS group #2
        Ic3, ic3;   // PPS group #2
        U1cts, u1cts;   // PPS group #2
        U2rx, u2rx;   // PPS group #2
        Sdi1, sdi1;   // PPS group #2
        Int2, int2;   // PPS group #3
        T4ck, t4ck;   // PPS group #3
        Ic1, ic1;   // PPS group #3
        Ic5, ic5;   // PPS group #3
        U1rx, u1rx;   // PPS group #3
        U2cts, u2cts;   // PPS group #3
        Sdi2, sdi2;   // PPS group #3
        Ocfb, ocfb;   // PPS group #3
        Int1, int1;   // PPS group #4
        T5ck, t5ck;   // PPS group #4
        Ic2, ic2;   // PPS group #4
        Ss2, ss2;   // PPS group #4
        Ocfa, ocfa;   // PPS group #4
    }{ // virtual output declarations
        C1out, c1out;
        C2out, c2out;
        C3out, c3out;
        Oc1, oc1;
        Oc2, oc2;
        Oc3, oc3;
        Oc4, oc4;
        Oc5, oc5;
        Refclko, refclko;
        Sdo1, sdo1;
        Sdo2, sdo2;
        Ss1, ss1;
        Ss2, ss2;
        U1rts, u1rts;
        U1tx, u1tx;
        U2rts, u2rts;
        U2tx, u2tx;
    }{ // virtual input mapping table
        Int4, int4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        T2ck, t2ckr { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ic4, ic4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ss1, ss1r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Refclki, refclkir { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Int3, int3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        T3ck, t3ckr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Ic3, ic3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        U1cts, u1ctsr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        U2rx, u2rxr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Sdi1, sdi1r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Int2, int2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        T4ck, t4ckr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic1, ic1r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic5, ic5r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U1rx, u1rxr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U2cts, u2ctsr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Sdi2, sdi2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ocfb, ocfbr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Int1, int1r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        T5ck, t5ckr { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ic2, ic2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ss2, ss2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ocfa, ocfar { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
    }{ // virtual output mapping table
        gpio::porta::RA0<MODE>, rpa0r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB3<MODE>, rpb3r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB4<MODE>, rpb4r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB15<MODE>, rpb15r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB7<MODE>, rpb7r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::porta::RA1<MODE>, rpa1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB5<MODE>, rpb5r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB1<MODE>, rpb1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB11<MODE>, rpb11r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB8<MODE>, rpb8r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::porta::RA2<MODE>, rpa2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB6<MODE>, rpb6r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA4<MODE>, rpa4r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB13<MODE>, rpb13r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB2<MODE>, rpb2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA3<MODE>, rpa3r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB14<MODE>, rpb14r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB0<MODE>, rpb0r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB10<MODE>, rpb10r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB9<MODE>, rpb9r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
    }
}

#[cfg(feature = "pic32mx2xxfxxxb")]
pps_tables! {
    { // virtual input declarations
        Int4, int4;   // PPS group #1
        T2ck, t2ck;   // PPS group #1
        Ic4, ic4;   // PPS group #1
        Ss1, ss1;   // PPS group #1
        Refclki, refclki;   // PPS group #1
        Int3, int3;   // PPS group #2
        T3ck, t3ck;   // PPS group #2
        Ic3, ic3;   // PPS group #2
        U1cts, u1cts;   // PPS group #2
        U2rx, u2rx;   // PPS group #2
        Sdi1, sdi1;   // PPS group #2
        Int2, int2;   // PPS group #3
        T4ck, t4ck;   // PPS group #3
        Ic1, ic1;   // PPS group #3
        Ic5, ic5;   // PPS group #3
        U1rx, u1rx;   // PPS group #3
        U2cts, u2cts;   // PPS group #3
        Sdi2, sdi2;   // PPS group #3
        Ocfb, ocfb;   // PPS group #3
        Int1, int1;   // PPS group #4
        T5ck, t5ck;   // PPS group #4
        Ic2, ic2;   // PPS group #4
        Ss2, ss2;   // PPS group #4
        Ocfa, ocfa;   // PPS group #4
    }{ // virtual output declarations
        C1out, c1out;
        C2out, c2out;
        C3out, c3out;
        Oc1, oc1;
        Oc2, oc2;
        Oc3, oc3;
        Oc4, oc4;
        Oc5, oc5;
        Refclko, refclko;
        Sdo1, sdo1;
        Sdo2, sdo2;
        Ss1, ss1;
        Ss2, ss2;
        U1rts, u1rts;
        U1tx, u1tx;
        U2rts, u2rts;
        U2tx, u2tx;
    }{ // virtual input mapping table
        Int4, int4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        T2ck, t2ckr { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ic4, ic4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ss1, ss1r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Refclki, refclkir { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Int3, int3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        T3ck, t3ckr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Ic3, ic3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        U1cts, u1ctsr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        U2rx, u2rxr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Sdi1, sdi1r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Int2, int2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        T4ck, t4ckr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic1, ic1r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic5, ic5r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U1rx, u1rxr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U2cts, u2ctsr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Sdi2, sdi2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ocfb, ocfbr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Int1, int1r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        T5ck, t5ckr { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ic2, ic2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ss2, ss2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ocfa, ocfar { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
    }{ // virtual output mapping table
        gpio::porta::RA0<MODE>, rpa0r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB3<MODE>, rpb3r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB4<MODE>, rpb4r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB15<MODE>, rpb15r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB7<MODE>, rpb7r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::porta::RA1<MODE>, rpa1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB5<MODE>, rpb5r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB1<MODE>, rpb1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB11<MODE>, rpb11r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB8<MODE>, rpb8r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::porta::RA2<MODE>, rpa2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA4<MODE>, rpa4r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB13<MODE>, rpb13r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB2<MODE>, rpb2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA3<MODE>, rpa3r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB14<MODE>, rpb14r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB0<MODE>, rpb0r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB10<MODE>, rpb10r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB9<MODE>, rpb9r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
    }
}

#[cfg(feature = "pic32mx2x4fxxxb")]
pps_tables! {
    { // virtual input declarations
        Int4, int4;   // PPS group #1
        T2ck, t2ck;   // PPS group #1
        Ic4, ic4;   // PPS group #1
        Ss1, ss1;   // PPS group #1
        Refclki, refclki;   // PPS group #1
        Int3, int3;   // PPS group #2
        T3ck, t3ck;   // PPS group #2
        Ic3, ic3;   // PPS group #2
        U1cts, u1cts;   // PPS group #2
        U2rx, u2rx;   // PPS group #2
        Sdi1, sdi1;   // PPS group #2
        Int2, int2;   // PPS group #3
        T4ck, t4ck;   // PPS group #3
        Ic1, ic1;   // PPS group #3
        Ic5, ic5;   // PPS group #3
        U1rx, u1rx;   // PPS group #3
        U2cts, u2cts;   // PPS group #3
        Sdi2, sdi2;   // PPS group #3
        Ocfb, ocfb;   // PPS group #3
        Int1, int1;   // PPS group #4
        T5ck, t5ck;   // PPS group #4
        Ic2, ic2;   // PPS group #4
        Ss2, ss2;   // PPS group #4
        Ocfa, ocfa;   // PPS group #4
    }{ // virtual output declarations
        C1out, c1out;
        C2out, c2out;
        C3out, c3out;
        Oc1, oc1;
        Oc2, oc2;
        Oc3, oc3;
        Oc4, oc4;
        Oc5, oc5;
        Refclko, refclko;
        Sdo1, sdo1;
        Sdo2, sdo2;
        Ss1, ss1;
        Ss2, ss2;
        U1rts, u1rts;
        U1tx, u1tx;
        U2rts, u2rts;
        U2tx, u2tx;
        Vbuson, vbuson;
    }{ // virtual input mapping table
        Int4, int4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        T2ck, t2ckr { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ic4, ic4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ss1, ss1r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Refclki, refclkir { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Int3, int3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        T3ck, t3ckr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        Ic3, ic3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        U1cts, u1ctsr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        U2rx, u2rxr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        Sdi1, sdi1r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        Int2, int2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        T4ck, t4ckr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic1, ic1r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic5, ic5r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U1rx, u1rxr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U2cts, u2ctsr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Sdi2, sdi2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ocfb, ocfbr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Int1, int1r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
        T5ck, t5ckr { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
        Ic2, ic2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
        Ss2, ss2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
        Ocfa, ocfar { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
    }{ // virtual output mapping table
        gpio::porta::RA0<MODE>, rpa0r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB3<MODE>, rpb3r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB4<MODE>, rpb4r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB15<MODE>, rpb15r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB7<MODE>, rpb7r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::porta::RA1<MODE>, rpa1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB5<MODE>, rpb5r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB1<MODE>, rpb1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB8<MODE>, rpb8r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::porta::RA2<MODE>, rpa2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA4<MODE>, rpa4r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB13<MODE>, rpb13r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB2<MODE>, rpb2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA3<MODE>, rpa3r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB14<MODE>, rpb14r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB0<MODE>, rpb0r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB9<MODE>, rpb9r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
    }
}

