//generated by edc2pps on 2023-06-18 09:59:08.655388+00:00

#[cfg(feature = "pic32mx1xxfxxxb")]
pps_tables! {
    { // virtual input declarations
        Int4, int4;   // PPS group #1
        T2ck, t2ck;   // PPS group #1
        Ic4, ic4;   // PPS group #1
        Ss1, ss1;   // PPS group #1
        Refclki, refclki;   // PPS group #1
        Int3, int3;   // PPS group #2
        T3ck, t3ck;   // PPS group #2
        Ic3, ic3;   // PPS group #2
        U1cts, u1cts;   // PPS group #2
        U2rx, u2rx;   // PPS group #2
        Sdi1, sdi1;   // PPS group #2
        Int2, int2;   // PPS group #3
        T4ck, t4ck;   // PPS group #3
        Ic1, ic1;   // PPS group #3
        Ic5, ic5;   // PPS group #3
        U1rx, u1rx;   // PPS group #3
        U2cts, u2cts;   // PPS group #3
        Sdi2, sdi2;   // PPS group #3
        Ocfb, ocfb;   // PPS group #3
        Int1, int1;   // PPS group #4
        T5ck, t5ck;   // PPS group #4
        Ic2, ic2;   // PPS group #4
        Ss2, ss2;   // PPS group #4
        Ocfa, ocfa;   // PPS group #4
    }{ // virtual output declarations
        C1out, c1out;
        C2out, c2out;
        C3out, c3out;
        Oc1, oc1;
        Oc2, oc2;
        Oc3, oc3;
        Oc4, oc4;
        Oc5, oc5;
        Refclko, refclko;
        Sdo1, sdo1;
        Sdo2, sdo2;
        Ss1, ss1;
        Ss2, ss2;
        U1rts, u1rts;
        U1tx, u1tx;
        U2rts, u2rts;
        U2tx, u2tx;
    }{ // virtual input mapping table
        Int4, int4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        T2ck, t2ckr { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ic4, ic4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ss1, ss1r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Refclki, refclkir { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Int3, int3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        T3ck, t3ckr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Ic3, ic3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        U1cts, u1ctsr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        U2rx, u2rxr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Sdi1, sdi1r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Int2, int2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        T4ck, t4ckr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic1, ic1r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic5, ic5r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U1rx, u1rxr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U2cts, u2ctsr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Sdi2, sdi2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ocfb, ocfbr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::portb::RB6<MODE>, 1;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Int1, int1r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        T5ck, t5ckr { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ic2, ic2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ss2, ss2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ocfa, ocfar { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
    }{ // virtual output mapping table
        gpio::porta::RA0<MODE>, rpa0r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB3<MODE>, rpb3r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB4<MODE>, rpb4r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB15<MODE>, rpb15r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB7<MODE>, rpb7r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::porta::RA1<MODE>, rpa1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB5<MODE>, rpb5r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB1<MODE>, rpb1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB11<MODE>, rpb11r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB8<MODE>, rpb8r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::porta::RA2<MODE>, rpa2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB6<MODE>, rpb6r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA4<MODE>, rpa4r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB13<MODE>, rpb13r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB2<MODE>, rpb2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA3<MODE>, rpa3r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB14<MODE>, rpb14r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB0<MODE>, rpb0r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB10<MODE>, rpb10r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB9<MODE>, rpb9r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
    }
}

#[cfg(feature = "pic32mx2xxfxxxb")]
pps_tables! {
    { // virtual input declarations
        Int4, int4;   // PPS group #1
        T2ck, t2ck;   // PPS group #1
        Ic4, ic4;   // PPS group #1
        Ss1, ss1;   // PPS group #1
        Refclki, refclki;   // PPS group #1
        Int3, int3;   // PPS group #2
        T3ck, t3ck;   // PPS group #2
        Ic3, ic3;   // PPS group #2
        U1cts, u1cts;   // PPS group #2
        U2rx, u2rx;   // PPS group #2
        Sdi1, sdi1;   // PPS group #2
        Int2, int2;   // PPS group #3
        T4ck, t4ck;   // PPS group #3
        Ic1, ic1;   // PPS group #3
        Ic5, ic5;   // PPS group #3
        U1rx, u1rx;   // PPS group #3
        U2cts, u2cts;   // PPS group #3
        Sdi2, sdi2;   // PPS group #3
        Ocfb, ocfb;   // PPS group #3
        Int1, int1;   // PPS group #4
        T5ck, t5ck;   // PPS group #4
        Ic2, ic2;   // PPS group #4
        Ss2, ss2;   // PPS group #4
        Ocfa, ocfa;   // PPS group #4
    }{ // virtual output declarations
        C1out, c1out;
        C2out, c2out;
        C3out, c3out;
        Oc1, oc1;
        Oc2, oc2;
        Oc3, oc3;
        Oc4, oc4;
        Oc5, oc5;
        Refclko, refclko;
        Sdo1, sdo1;
        Sdo2, sdo2;
        Ss1, ss1;
        Ss2, ss2;
        U1rts, u1rts;
        U1tx, u1tx;
        U2rts, u2rts;
        U2tx, u2tx;
    }{ // virtual input mapping table
        Int4, int4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        T2ck, t2ckr { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ic4, ic4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ss1, ss1r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Refclki, refclkir { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Int3, int3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        T3ck, t3ckr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Ic3, ic3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        U1cts, u1ctsr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        U2rx, u2rxr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Sdi1, sdi1r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB11<MODE>, 3;
            gpio::portb::RB8<MODE>, 4;
        }
        Int2, int2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        T4ck, t4ckr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic1, ic1r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic5, ic5r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U1rx, u1rxr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U2cts, u2ctsr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Sdi2, sdi2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ocfb, ocfbr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Int1, int1r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        T5ck, t5ckr { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ic2, ic2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ss2, ss2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
        Ocfa, ocfar { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB10<MODE>, 3;
            gpio::portb::RB9<MODE>, 4;
        }
    }{ // virtual output mapping table
        gpio::porta::RA0<MODE>, rpa0r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB3<MODE>, rpb3r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB4<MODE>, rpb4r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB15<MODE>, rpb15r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB7<MODE>, rpb7r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::porta::RA1<MODE>, rpa1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB5<MODE>, rpb5r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB1<MODE>, rpb1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB11<MODE>, rpb11r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB8<MODE>, rpb8r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::porta::RA2<MODE>, rpa2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA4<MODE>, rpa4r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB13<MODE>, rpb13r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB2<MODE>, rpb2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA3<MODE>, rpa3r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB14<MODE>, rpb14r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB0<MODE>, rpb0r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB10<MODE>, rpb10r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB9<MODE>, rpb9r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
    }
}

#[cfg(feature = "pic32mx2x4fxxxb")]
pps_tables! {
    { // virtual input declarations
        Int4, int4;   // PPS group #1
        T2ck, t2ck;   // PPS group #1
        Ic4, ic4;   // PPS group #1
        Ss1, ss1;   // PPS group #1
        Refclki, refclki;   // PPS group #1
        Int3, int3;   // PPS group #2
        T3ck, t3ck;   // PPS group #2
        Ic3, ic3;   // PPS group #2
        U1cts, u1cts;   // PPS group #2
        U2rx, u2rx;   // PPS group #2
        Sdi1, sdi1;   // PPS group #2
        Int2, int2;   // PPS group #3
        T4ck, t4ck;   // PPS group #3
        Ic1, ic1;   // PPS group #3
        Ic5, ic5;   // PPS group #3
        U1rx, u1rx;   // PPS group #3
        U2cts, u2cts;   // PPS group #3
        Sdi2, sdi2;   // PPS group #3
        Ocfb, ocfb;   // PPS group #3
        Int1, int1;   // PPS group #4
        T5ck, t5ck;   // PPS group #4
        Ic2, ic2;   // PPS group #4
        Ss2, ss2;   // PPS group #4
        Ocfa, ocfa;   // PPS group #4
    }{ // virtual output declarations
        C1out, c1out;
        C2out, c2out;
        C3out, c3out;
        Oc1, oc1;
        Oc2, oc2;
        Oc3, oc3;
        Oc4, oc4;
        Oc5, oc5;
        Refclko, refclko;
        Sdo1, sdo1;
        Sdo2, sdo2;
        Ss1, ss1;
        Ss2, ss2;
        U1rts, u1rts;
        U1tx, u1tx;
        U2rts, u2rts;
        U2tx, u2tx;
        Vbuson, vbuson;
    }{ // virtual input mapping table
        Int4, int4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        T2ck, t2ckr { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ic4, ic4r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Ss1, ss1r { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Refclki, refclkir { // PPS group #1
            gpio::porta::RA0<MODE>, 0;
            gpio::portb::RB3<MODE>, 1;
            gpio::portb::RB4<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portb::RB7<MODE>, 4;
        }
        Int3, int3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        T3ck, t3ckr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        Ic3, ic3r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        U1cts, u1ctsr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        U2rx, u2rxr { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        Sdi1, sdi1r { // PPS group #2
            gpio::porta::RA1<MODE>, 0;
            gpio::portb::RB5<MODE>, 1;
            gpio::portb::RB1<MODE>, 2;
            gpio::portb::RB8<MODE>, 4;
        }
        Int2, int2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        T4ck, t4ckr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic1, ic1r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ic5, ic5r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U1rx, u1rxr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        U2cts, u2ctsr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Sdi2, sdi2r { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Ocfb, ocfbr { // PPS group #3
            gpio::porta::RA2<MODE>, 0;
            gpio::porta::RA4<MODE>, 2;
            gpio::portb::RB13<MODE>, 3;
            gpio::portb::RB2<MODE>, 4;
        }
        Int1, int1r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
        T5ck, t5ckr { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
        Ic2, ic2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
        Ss2, ss2r { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
        Ocfa, ocfar { // PPS group #4
            gpio::porta::RA3<MODE>, 0;
            gpio::portb::RB14<MODE>, 1;
            gpio::portb::RB0<MODE>, 2;
            gpio::portb::RB9<MODE>, 4;
        }
    }{ // virtual output mapping table
        gpio::porta::RA0<MODE>, rpa0r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB3<MODE>, rpb3r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB4<MODE>, rpb4r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB15<MODE>, rpb15r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::portb::RB7<MODE>, rpb7r {    // PPS group #1
            U1tx, 1;
            U2rts, 2;
            Vbuson, 2;
            Ss1, 3;
            Oc1, 5;
            C2out, 7;
        }
        gpio::porta::RA1<MODE>, rpa1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB5<MODE>, rpb5r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB1<MODE>, rpb1r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::portb::RB8<MODE>, rpb8r {    // PPS group #2
            Sdo1, 3;
            Sdo2, 4;
            Oc2, 5;
            C3out, 7;
        }
        gpio::porta::RA2<MODE>, rpa2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA4<MODE>, rpa4r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB13<MODE>, rpb13r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::portb::RB2<MODE>, rpb2r {    // PPS group #3
            Sdo1, 3;
            Sdo2, 4;
            Oc4, 5;
            Oc5, 6;
            Refclko, 7;
        }
        gpio::porta::RA3<MODE>, rpa3r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB14<MODE>, rpb14r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB0<MODE>, rpb0r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
        gpio::portb::RB9<MODE>, rpb9r {    // PPS group #4
            U1rts, 1;
            U2tx, 2;
            Ss2, 4;
            Oc3, 5;
            C1out, 7;
        }
    }
}

#[cfg(feature = "pic32mx37x")]
pps_tables! {
    { // virtual input declarations
        Int3, int3;   // PPS group #1
        T2ck, t2ck;   // PPS group #1
        Ic3, ic3;   // PPS group #1
        U1rx, u1rx;   // PPS group #1
        U2rx, u2rx;   // PPS group #1
        U5cts, u5cts;   // PPS group #1
        Refclki, refclki;   // PPS group #1
        Int4, int4;   // PPS group #2
        T5ck, t5ck;   // PPS group #2
        Ic4, ic4;   // PPS group #2
        U3rx, u3rx;   // PPS group #2
        U4cts, u4cts;   // PPS group #2
        Sdi1, sdi1;   // PPS group #2
        Sdi2, sdi2;   // PPS group #2
        Int2, int2;   // PPS group #3
        T4ck, t4ck;   // PPS group #3
        Ic2, ic2;   // PPS group #3
        Ic5, ic5;   // PPS group #3
        U1cts, u1cts;   // PPS group #3
        U2cts, u2cts;   // PPS group #3
        Ss1, ss1;   // PPS group #3
        Int1, int1;   // PPS group #4
        T3ck, t3ck;   // PPS group #4
        Ic1, ic1;   // PPS group #4
        U3cts, u3cts;   // PPS group #4
        U4rx, u4rx;   // PPS group #4
        U5rx, u5rx;   // PPS group #4
        Ss2, ss2;   // PPS group #4
        Ocfa, ocfa;   // PPS group #4
    }{ // virtual output declarations
        C1out, c1out;
        C2out, c2out;
        Oc1, oc1;
        Oc2, oc2;
        Oc3, oc3;
        Oc4, oc4;
        Oc5, oc5;
        Refclko, refclko;
        Sdo1, sdo1;
        Sdo2, sdo2;
        Ss1, ss1;
        Ss2, ss2;
        U1rts, u1rts;
        U1tx, u1tx;
        U2rts, u2rts;
        U2tx, u2tx;
        U3rts, u3rts;
        U3tx, u3tx;
        U4rts, u4rts;
        U4tx, u4tx;
        U5rts, u5rts;
        U5tx, u5tx;
    }{ // virtual input mapping table
        Int3, int3r { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        T2ck, t2ckr { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        Ic3, ic3r { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        U1rx, u1rxr { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        U2rx, u2rxr { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        U5cts, u5ctsr { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        Refclki, refclkir { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        Int4, int4r { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF7<MODE>, 15;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        T5ck, t5ckr { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF7<MODE>, 15;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        Ic4, ic4r { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF7<MODE>, 15;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        U3rx, u3rxr { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF7<MODE>, 15;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        U4cts, u4ctsr { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF7<MODE>, 15;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        Sdi1, sdi1r { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF7<MODE>, 15;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        Sdi2, sdi2r { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF7<MODE>, 15;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        Int2, int2r { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        T4ck, t4ckr { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        Ic2, ic2r { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        Ic5, ic5r { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        U1cts, u1ctsr { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        U2cts, u2ctsr { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        Ss1, ss1r { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        Int1, int1r { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        T3ck, t3ckr { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        Ic1, ic1r { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        U3cts, u3ctsr { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        U4rx, u4rxr { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        U5rx, u5rxr { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        Ss2, ss2r { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        Ocfa, ocfar { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
    }{ // virtual output mapping table
        gpio::portd::RD2<MODE>, rpd2r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portg::RG8<MODE>, rpg8r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portc::RC1<MODE>, rpc1r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portd::RD14<MODE>, rpd14r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portg::RG1<MODE>, rpg1r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::porta::RA14<MODE>, rpa14r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portf::RF2<MODE>, rpf2r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portf::RF4<MODE>, rpf4r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portd::RD10<MODE>, rpd10r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portf::RF1<MODE>, rpf1r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portb::RB9<MODE>, rpb9r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portb::RB10<MODE>, rpb10r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portc::RC14<MODE>, rpc14r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portb::RB5<MODE>, rpb5r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portd::RD3<MODE>, rpd3r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portg::RG7<MODE>, rpg7r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portc::RC4<MODE>, rpc4r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD15<MODE>, rpd15r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portg::RG0<MODE>, rpg0r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::porta::RA15<MODE>, rpa15r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portf::RF5<MODE>, rpf5r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD11<MODE>, rpd11r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portf::RF0<MODE>, rpf0r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portb::RB1<MODE>, rpb1r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::porte::RE5<MODE>, rpe5r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portc::RC13<MODE>, rpc13r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portb::RB3<MODE>, rpb3r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD9<MODE>, rpd9r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portg::RG6<MODE>, rpg6r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portd::RD12<MODE>, rpd12r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portf::RF8<MODE>, rpf8r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portc::RC3<MODE>, rpc3r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::porte::RE9<MODE>, rpe9r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB2<MODE>, rpb2r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB8<MODE>, rpb8r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB15<MODE>, rpb15r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portd::RD4<MODE>, rpd4r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB0<MODE>, rpb0r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::porte::RE3<MODE>, rpe3r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB7<MODE>, rpb7r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portf::RF12<MODE>, rpf12r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portd::RD1<MODE>, rpd1r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portg::RG9<MODE>, rpg9r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portc::RC2<MODE>, rpc2r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::porte::RE8<MODE>, rpe8r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portb::RB14<MODE>, rpb14r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD0<MODE>, rpd0r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD8<MODE>, rpd8r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portb::RB6<MODE>, rpb6r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD5<MODE>, rpd5r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portf::RF3<MODE>, rpf3r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portf::RF13<MODE>, rpf13r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
    }
}

#[cfg(feature = "pic32mx47x")]
pps_tables! {
    { // virtual input declarations
        Int3, int3;   // PPS group #1
        T2ck, t2ck;   // PPS group #1
        Ic3, ic3;   // PPS group #1
        U1rx, u1rx;   // PPS group #1
        U2rx, u2rx;   // PPS group #1
        U5cts, u5cts;   // PPS group #1
        Refclki, refclki;   // PPS group #1
        Int4, int4;   // PPS group #2
        T5ck, t5ck;   // PPS group #2
        Ic4, ic4;   // PPS group #2
        U3rx, u3rx;   // PPS group #2
        U4cts, u4cts;   // PPS group #2
        Sdi1, sdi1;   // PPS group #2
        Sdi2, sdi2;   // PPS group #2
        Int2, int2;   // PPS group #3
        T4ck, t4ck;   // PPS group #3
        Ic2, ic2;   // PPS group #3
        Ic5, ic5;   // PPS group #3
        U1cts, u1cts;   // PPS group #3
        U2cts, u2cts;   // PPS group #3
        Ss1, ss1;   // PPS group #3
        Int1, int1;   // PPS group #4
        T3ck, t3ck;   // PPS group #4
        Ic1, ic1;   // PPS group #4
        U3cts, u3cts;   // PPS group #4
        U4rx, u4rx;   // PPS group #4
        U5rx, u5rx;   // PPS group #4
        Ss2, ss2;   // PPS group #4
        Ocfa, ocfa;   // PPS group #4
    }{ // virtual output declarations
        C1out, c1out;
        C2out, c2out;
        Oc1, oc1;
        Oc2, oc2;
        Oc3, oc3;
        Oc4, oc4;
        Oc5, oc5;
        Refclko, refclko;
        Sdo1, sdo1;
        Sdo2, sdo2;
        Ss1, ss1;
        Ss2, ss2;
        U1rts, u1rts;
        U1tx, u1tx;
        U2rts, u2rts;
        U2tx, u2tx;
        U3rts, u3rts;
        U3tx, u3tx;
        U4rts, u4rts;
        U4tx, u4tx;
        U5rts, u5rts;
        U5tx, u5tx;
    }{ // virtual input mapping table
        Int3, int3r { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        T2ck, t2ckr { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        Ic3, ic3r { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        U1rx, u1rxr { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        U2rx, u2rxr { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        U5cts, u5ctsr { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        Refclki, refclkir { // PPS group #1
            gpio::portd::RD2<MODE>, 0;
            gpio::portg::RG8<MODE>, 1;
            gpio::portc::RC1<MODE>, 10;
            gpio::portd::RD14<MODE>, 11;
            gpio::portg::RG1<MODE>, 12;
            gpio::porta::RA14<MODE>, 13;
            gpio::portf::RF2<MODE>, 15;
            gpio::portf::RF4<MODE>, 2;
            gpio::portd::RD10<MODE>, 3;
            gpio::portf::RF1<MODE>, 4;
            gpio::portb::RB9<MODE>, 5;
            gpio::portb::RB10<MODE>, 6;
            gpio::portc::RC14<MODE>, 7;
            gpio::portb::RB5<MODE>, 8;
        }
        Int4, int4r { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        T5ck, t5ckr { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        Ic4, ic4r { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        U3rx, u3rxr { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        U4cts, u4ctsr { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        Sdi1, sdi1r { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        Sdi2, sdi2r { // PPS group #2
            gpio::portd::RD3<MODE>, 0;
            gpio::portg::RG7<MODE>, 1;
            gpio::portc::RC4<MODE>, 10;
            gpio::portd::RD15<MODE>, 11;
            gpio::portg::RG0<MODE>, 12;
            gpio::porta::RA15<MODE>, 13;
            gpio::portf::RF5<MODE>, 2;
            gpio::portd::RD11<MODE>, 3;
            gpio::portf::RF0<MODE>, 4;
            gpio::portb::RB1<MODE>, 5;
            gpio::porte::RE5<MODE>, 6;
            gpio::portc::RC13<MODE>, 7;
            gpio::portb::RB3<MODE>, 8;
        }
        Int2, int2r { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        T4ck, t4ckr { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        Ic2, ic2r { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        Ic5, ic5r { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        U1cts, u1ctsr { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        U2cts, u2ctsr { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        Ss1, ss1r { // PPS group #3
            gpio::portd::RD9<MODE>, 0;
            gpio::portg::RG6<MODE>, 1;
            gpio::portd::RD12<MODE>, 10;
            gpio::portf::RF8<MODE>, 11;
            gpio::portc::RC3<MODE>, 12;
            gpio::porte::RE9<MODE>, 13;
            gpio::portb::RB2<MODE>, 15;
            gpio::portb::RB8<MODE>, 2;
            gpio::portb::RB15<MODE>, 3;
            gpio::portd::RD4<MODE>, 4;
            gpio::portb::RB0<MODE>, 5;
            gpio::porte::RE3<MODE>, 6;
            gpio::portb::RB7<MODE>, 7;
            gpio::portf::RF12<MODE>, 9;
        }
        Int1, int1r { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        T3ck, t3ckr { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        Ic1, ic1r { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        U3cts, u3ctsr { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        U4rx, u4rxr { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        U5rx, u5rxr { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        Ss2, ss2r { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
        Ocfa, ocfar { // PPS group #4
            gpio::portd::RD1<MODE>, 0;
            gpio::portg::RG9<MODE>, 1;
            gpio::portc::RC2<MODE>, 12;
            gpio::porte::RE8<MODE>, 13;
            gpio::portb::RB14<MODE>, 2;
            gpio::portd::RD0<MODE>, 3;
            gpio::portd::RD8<MODE>, 4;
            gpio::portb::RB6<MODE>, 5;
            gpio::portd::RD5<MODE>, 6;
            gpio::portf::RF3<MODE>, 8;
            gpio::portf::RF13<MODE>, 9;
        }
    }{ // virtual output mapping table
        gpio::portd::RD2<MODE>, rpd2r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portg::RG8<MODE>, rpg8r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portc::RC1<MODE>, rpc1r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portd::RD14<MODE>, rpd14r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portg::RG1<MODE>, rpg1r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::porta::RA14<MODE>, rpa14r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portf::RF2<MODE>, rpf2r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portf::RF4<MODE>, rpf4r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portd::RD10<MODE>, rpd10r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portf::RF1<MODE>, rpf1r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portb::RB9<MODE>, rpb9r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portb::RB10<MODE>, rpb10r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portc::RC14<MODE>, rpc14r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portb::RB5<MODE>, rpb5r {    // PPS group #1
            U3tx, 1;
            Oc3, 11;
            C2out, 13;
            U4rts, 2;
            Sdo2, 6;
        }
        gpio::portd::RD3<MODE>, rpd3r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portg::RG7<MODE>, rpg7r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portc::RC4<MODE>, rpc4r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD15<MODE>, rpd15r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portg::RG0<MODE>, rpg0r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::porta::RA15<MODE>, rpa15r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portf::RF5<MODE>, rpf5r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD11<MODE>, rpd11r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portf::RF0<MODE>, rpf0r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portb::RB1<MODE>, rpb1r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::porte::RE5<MODE>, rpe5r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portc::RC13<MODE>, rpc13r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portb::RB3<MODE>, rpb3r {    // PPS group #2
            U2tx, 1;
            Oc4, 11;
            U1tx, 3;
            U5rts, 4;
            Sdo2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD9<MODE>, rpd9r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portg::RG6<MODE>, rpg6r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portd::RD12<MODE>, rpd12r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portf::RF8<MODE>, rpf8r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portc::RC3<MODE>, rpc3r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::porte::RE9<MODE>, rpe9r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB2<MODE>, rpb2r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB8<MODE>, rpb8r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB15<MODE>, rpb15r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portd::RD4<MODE>, rpd4r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB0<MODE>, rpb0r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::porte::RE3<MODE>, rpe3r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portb::RB7<MODE>, rpb7r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portf::RF12<MODE>, rpf12r {    // PPS group #3
            U3rts, 1;
            Oc5, 11;
            C1out, 13;
            U4tx, 2;
            Refclko, 3;
            U5tx, 4;
            Ss1, 7;
            Sdo1, 8;
        }
        gpio::portd::RD1<MODE>, rpd1r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portg::RG9<MODE>, rpg9r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portc::RC2<MODE>, rpc2r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::porte::RE8<MODE>, rpe8r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portb::RB14<MODE>, rpb14r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD0<MODE>, rpd0r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD8<MODE>, rpd8r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portb::RB6<MODE>, rpb6r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portd::RD5<MODE>, rpd5r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
        gpio::portf::RF13<MODE>, rpf13r {    // PPS group #4
            U2rts, 1;
            Oc2, 11;
            Oc1, 12;
            U1rts, 3;
            U5tx, 4;
            Ss2, 6;
            Sdo1, 8;
        }
    }
}

